setwd("/Users/ton/r")
consumption <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
png(filename = "ExData_Plotting1/plot3.png", width=480, height=480)
consumption$DateTime <- paste(consumption$Date, consumption$Time, sep=" ")
consumption$DateTime <- strptime(consumption$DateTime, "%d/%m/%Y %H:%M:%S")
consumption$Date <- as.Date(consumption$Date, "%d/%m/%Y")
consumption <- subset(consumption, consumption$Date == "2007-02-01" | consumption$Date == "2007-02-02")
consumption$Sub_metering_1 <- as.numeric(consumption$Sub_metering_1)
consumption$Sub_metering_2 <- as.numeric(consumption$Sub_metering_2)
consumption$Sub_metering_3 <- as.numeric(consumption$Sub_metering_3)
plot(consumption$DateTime, consumption$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(consumption$DateTime, consumption$Sub_metering_2, col="red")
lines(consumption$DateTime, consumption$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=2)
dev.off()