setwd("/Users/ton/r")
consumption <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
png(filename = "ExData_Plotting1/plot1.png", width=480, height=480)
consumption$DateTime <- paste(consumption$Date, consumption$Time, sep=" ")
consumption$DateTime <- strptime(consumption$DateTime, "%d/%m/%Y %H:%M:%S")
consumption$Date <- as.Date(consumption$Date, "%d/%m/%Y")
consumption$Global_active_power <- as.numeric(consumption$Global_active_power)
consumption <- subset(consumption, consumption$Date == "2007-02-01" | consumption$Date == "2007-02-02")
hist(consumption$Global_active_power, main="Global Active Power", xlab="Global Active Power (kilowatts)", col="red")
dev.off()