setwd("/Users/ton/r")
consumption <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
png(filename = "ExData_Plotting1/plot4.png", width=480, height=480)
consumption$DateTime <- paste(consumption$Date, consumption$Time, sep=" ")
consumption$DateTime <- strptime(consumption$DateTime, "%d/%m/%Y %H:%M:%S")
consumption$Date <- as.Date(consumption$Date, "%d/%m/%Y")
consumption$Global_active_power <- as.numeric(consumption$Global_active_power)
consumption$Voltage <- as.numeric(consumption$Voltage)
consumption$Global_reactive_power <- as.numeric(consumption$Global_reactive_power)
consumption <- subset(consumption, consumption$Date == "2007-02-01" | consumption$Date == "2007-02-02")

par(mfrow=c(2,2))
plot(consumption$DateTime, consumption$Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(consumption$DateTime, consumption$Voltage, type="l", col="black", xlab="datetime", ylab="Voltage")
plot(consumption$DateTime, consumption$Sub_metering_1, type="l", col="black", xlab="", ylab="Energy sub metering")
lines(consumption$DateTime, consumption$Sub_metering_2, col="red")
lines(consumption$DateTime, consumption$Sub_metering_3, col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col=c("black", "red", "blue"), lwd=2, bty = "n")
plot(consumption$DateTime, consumption$Global_reactive_power, type="l", col="black", xlab="datetime", ylab="Global_reactive_power")
dev.off()